Develop
justfriendlyneighbor/intelligent_placer pull request #1
Opened 2022-09-17 20:05 UTC by justfriendlyneighbor

Добавлено описание работы, датасет примитивов, датасет изображений с примерами верной и неверной работы программы.

2022-10-15 01:11 UTC, PIDAMI reviewed
Что понравилось:
+ Комментарий в конце плана про задачу двумерной упаковки

Что не очень понравилось:
+ [Предмет](https://github.com/justfriendlyneighbor/intelligent_placer/blob/develop/Primitives/2.JPG)
дает сильные тени и блики как на изображении, с которым сравниваются входные данные, так и на изображениях из тестовых кейсов, могут возникнуть проблемы в дальнейшем
+ Ограничений на количество вершин многоугольника нет, хотя кажется, что логично их иметь ради перформанса
+ Рельеф поверхности может помешать алгоритму (вертикальная складка примерно посередине)

2022-10-15 01:11 UTC, PIDAMI commented on README.md
> +- Для нахождения многоугольника на листе применить фильтр Canny или/и фильтр Гауса. Также найти площадь многоугольника и его бинарную маску.
Подробнее бы расписать, как конкретно находится многоугольник. Как после применения фильтра Кэнни отличается многоугольник от предметов?

2022-10-15 01:11 UTC, PIDAMI commented on README.md
> ++ Проверить какие получится требования (например замкнутость и выпуклость многоугольника или непересечение предметов, размерности предметов не превышают размеры многоугольника)
А что с требованиями, которые не получится проверить? И о каких размерностях предметов идет речь - разве мы заранее не знаем, что все предметы трехмерные?

2022-10-15 01:11 UTC, PIDAMI commented on README.md
> ++ Отсортировать предметы по убыванию площади (порядок необходимо протестировать) и по этому списку для каждого:
Не понятно, что значит текст в скобках

2022-10-15 08:33 UTC, ITrosh requested changes

2022-10-15 08:33 UTC, ITrosh commented on README.md
> +- Многоугольник нарисован черным маркером на белой бумаге
Нет ограничения на число вершин многоугольника, возможно его стоит задать?

2022-10-15 09:04 UTC, ITrosh requested changes

2022-10-15 09:04 UTC, ITrosh commented on README.md
> +- Результатом работы программы является ответ True, если удается поместить предметы в многоугольник, или False, если не удается поместить предметы в многоугольник.
Для достоверности результата, помимо возврата логического значения, возможно стоит выводить и картинку, на которой отражается ответ.

2022-10-15 09:11 UTC, ITrosh commented on README.md
> +- Результатом работы программы является ответ True, если удается поместить предметы в многоугольник, или False, если не удается поместить предметы в многоугольник.
Возможно для более достоверного решения, помимо возврата логического значения, стоит выводить и картинку, отражающую ответ.

2022-10-15 09:11 UTC, ITrosh commented on README.md
> +- Предметы могут быть только из заранее заданного тренировочного датасета и могут быть расположены на закрепленной оранжевой поверхности (той же что была использована при фотографировании тренировочн
На используемой поверхности есть складка, которая может вносить ошибку в результаты работы тестовых примеров, возможно стоит несколько видоизменить поверхность?

2022-10-15 09:11 UTC, ITrosh commented on README.md
> +- Многоугольник нарисован черным маркером на белой бумаге
А какие требования к числу вершин многоугольника? Лучше, наверное, их указать.

2022-10-15 13:02 UTC, MihailTchekmarev commented on README.md
> +- Предметы и многоугольник должны целиком быть на одной фотографии
Должен ли лист А4 также быть на фотографии целиком, или можно обойтись без этого?

2022-10-15 13:02 UTC, MihailTchekmarev commented on README.md
> +- Предметы не могут пересекаться с многоугольником
Что насчет теней и бликов? Один из объектов довольно блестящий - не создаст ли это помех или гарантируется корректная обработка?

2022-10-15 13:02 UTC, MihailTchekmarev commented on README.md
> +- Для нахождения предметов провести бинаризацию и сегментацию изображения, сопоставить с шаблонами дескриптором SIFT. Также найти площади предметов.
Как в алгоритме будет применяться информация о сопоставлении с шаблонами? И так ли необходимо находить площади предметов, если это используется только для задания порядка укладки? В следующем пункте говорится о нахождении линейных размерностей, возможно стоит воспользоваться ими, тем более, что они позволят отсечь самые простые False случаи?

2022-10-15 13:02 UTC, MihailTchekmarev commented on README.md
> +  + Переносим предмет к углу многоугольника, при необходимости применив матрицу поворота. Если объект присоединить не получится то пробуем сдвигать его на небольшой заданный шаг от границ куда пытаем
В данной формулировке не ясно, как выбирается 'угол', направление сдвига и поворота. Возможно, в следующих итерациях стоит добавить соображения по этому поводу.

2022-10-27 14:08 UTC, justfriendlyneighbor commented on README.md
> +- Для нахождения многоугольника на листе применить фильтр Canny или/и фильтр Гауса. Также найти площадь многоугольника и его бинарную маску.
Добавил примерные пункты решения данной задачи. Кроме этого стоит заметить что предметы не находятся на листе А4.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> ++ Проверить какие получится требования (например замкнутость и выпуклость многоугольника или непересечение предметов, размерности предметов не превышают размеры многоугольника)
Убрал замечание про требования. Про размерности имеется в виду сравнение размеров некоего многоугольника (1) (наверное следует применить требования к многоугольнику (2) также к (1)) описывающего маску предмета с размерами многоугольника на листе (2).

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> ++ Отсортировать предметы по убыванию площади (порядок необходимо протестировать) и по этому списку для каждого:
Убрал данное замечание.
Также добавил ограничения на число вершин многоугольника. По поводу предмета и поверхности решил рассмотреть необходимость изменений в дальнейших итерациях.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +- Результатом работы программы является ответ True, если удается поместить предметы в многоугольник, или False, если не удается поместить предметы в многоугольник.
Спасибо за предложение, попробую добавить такую картинку, если не возникнут технические трудности.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +- Предметы могут быть только из заранее заданного тренировочного датасета и могут быть расположены на закрепленной оранжевой поверхности (той же что была использована при фотографировании тренировочн
По поводу поверхности решил рассмотреть необходимость изменений в дальнейших итерациях.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +- Многоугольник нарисован черным маркером на белой бумаге
Добавил ограничения на число вершин многоугольника.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +- Предметы и многоугольник должны целиком быть на одной фотографии
Если лист А4 будет на фотографии не целиком возможна ситуация, когда многоугольник полностью находится на листе но не полностью на фотографии. Если же это не так, то такая фотография возможно подходит для данной задачи.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +- Предметы не могут пересекаться с многоугольником
По поводу предмета и поверхности решил рассмотреть необходимость изменений в дальнейших итерациях.

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +- Для нахождения предметов провести бинаризацию и сегментацию изображения, сопоставить с шаблонами дескриптором SIFT. Также найти площади предметов.
Сопоставление с шаблонами необходимо для проверки, того что используемые предметы принадлежат тренировочному датасету. По поводу площадей и линейных размерностей: неясно возможны ли случаи когда только линейные размерности, помогут отсечь простейшие случаи. Также мы сортируем предметы по площади при укладке

2022-10-27 14:09 UTC, justfriendlyneighbor commented on README.md
> +  + Переносим предмет к углу многоугольника, при необходимости применив матрицу поворота. Если объект присоединить не получится то пробуем сдвигать его на небольшой заданный шаг от границ куда пытаем
Уточню данное замечание в дальнейших итерациях.

2022-10-27 14:18 UTC, merged